name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4
      - name: Set sdk.dir
        working-directory: android
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug
      - name: List APK outputs
        run: |
          ls -R android/app/build/outputs || true
          find android/app/build/outputs -name "*.apk" -ls || true
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/**/*.apk
